#!/usr/bin/env php
<?php

use HedgeBot\Core\HedgeBot;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/Core/HedgeBot.php';

spl_autoload_register([HedgeBot::class, 'autoload']);

const ENV = "console";

use Symfony\Component\Console\Application;
use HedgeBot\Core\Console\ConsoleProvider;

$application = new Application();

$provider = new ConsoleProvider($argv);
$provider->populateApplication($application);

$application->run();
