<?php

/**
 * Quick and dirty file fetcher, to be able to fetch files generated by the Horaro Text File plugin over networks.
 */

$opts = "i:o:t:";
$longopts = [
    "input:",
    "output:",
    "time:"
];

$options = getopt($opts, $longopts);

$input = $options['i'] ?? $options['input'] ?? null;
$output = $options['o'] ?? $options['output'] ?? null;
$time = $options['t'] ?? $options['time'] ?? 1;

if (empty($input) || empty($output)) {
    die("Missing input or output file.\n");
}

while (true) {
    file_put_contents($output, file_get_contents($input));
    sleep($time);
}
