<?php

namespace HedgeBot\Core\Events;

use HedgeBot\Core\Traits\Hydrator;

/**
 * Class ServerEvent
 * @package HedgeBot\Core\Events
 */
class ServerEvent extends Event
{
    /** @inheritDoc */
    const BROADCAST = false;
    
    protected $membership;
    protected $nick;
    protected $user;
    protected $command;
    protected $channel;
    protected $additionnal;
    protected $message;
    protected $raw;
    protected $moderator;

    use Hydrator;

    /**
     * Creates a server event from the data array generated by IRCConnection::parseMsg().
     *
     * @constructor
     * @param       array $command The data array, using IRCConnection::parseMsg() keys.
     */
    public function __construct(array $command)
    {
        parent::__construct($command['command']);
        $this->hydrate($command);
    }

    /**
     * @return string
     */
    public static function getType()
    {
        return 'serverEvent';
    }
}
